runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /nvd3
  static_dir: nvd3
  secure: always
- url: /semantic/dist
  static_dir: semantic/dist
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /
  script: big-goals-tracker-main.app
  secure: always
- url: /old
  script: big-goals-tracker-main.app
  secure: always
- url: /save
  script: big-goals-tracker-save.app
  secure: always
- url: /getold
  script: big-goals-tracker-save.app
  secure: always
- url: /unsubmitted
  script: big-goals-tracker-save.app
  secure: always
- url: /.*
  script: inexistent.app
  secure: always

skip_files:
- ^nodes_modules/.*
- ^LICENSE
- ^semantic/gulpfile.js
- ^semantic/src/.*
- ^semantic/tasks/.*

libraries:
- name: webapp2
  version: latest
