runtime: python312
app_engine_apis: true

handlers:
- url: /nvd3
  static_dir: nvd3
  secure: always
- url: /semantic/dist
  static_dir: semantic/dist
  secure: always
- url: /images
  static_dir: images
  secure: always
- url: /
  script: main.app
  secure: always
- url: /old
  script: main.app
  secure: always
- url: /save
  script: save.app
  secure: always
- url: /getold
  script: save.app
  secure: always
- url: /unsubmitted
  script: save.app
  secure: always
- url: /.*
  script: inexistent.app
  secure: always
